name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo test
      # build for no_std to catch errors
      - run: cargo +nightly build --no-default-features
      - run: cargo +nightly test --no-default-features
      # build for no_std to catch errors
      - run: cargo +nightly build --no-default-features --features alloc
      - run: cargo +nightly test --no-default-features --features alloc
